sudo: required
services:
  - docker

before_install:
  - docker build -t klyners/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true klyners/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket-name: "elasticbeanstalk-eu-north-1-593793046006"
  bucket-path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY$
  secret_access_key: "$AWS_SECRET_KEY$"